apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-mesh-aoa/
    targetRevision: scratchspace-v1
    path: environment/wave-4/prod/active/gloo-mesh-2.1.0-beta18-crds/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true