# charts - each key is a helm chart install
charts:

  crossplane:
    namespace: crossplane-system
    repo: https://charts.crossplane.io/stable
    chart: crossplane
    revision: "1.10.0"

  crossplane-setup:
    namespace: crossplane-system
    repo: https://github.com/bdlilley/gloo-mesh-aoa.git
    path: charts/helm-aoa
    syncPolicy:
      syncOptions: [] # dont create namespace

defaults:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true