apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: admin-workspace-settings
  namespace: gloo-mesh
spec:
  exportTo:
  - resources:
    - kind: SERVICE
      labels:
        app.kubernetes.io/name: argocd-server
    - kind: SERVICE
      labels:
        app.kubernetes.io/name: grafana
    - kind: SERVICE
      labels:
        app: gloo-mesh-ui
    - kind: ALL
      labels:
        expose: "true"
    workspaces:
    - name: gateways
  importFrom:
  - resources:
    - kind: SERVICE
    workspaces:
    - name: gateways
  options:
    federation:
      enabled: true
      hostSuffix: global