# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- argocd-ns.yaml
- bookinfo-backends-ns.yaml
- bookinfo-frontends-ns.yaml
- gloo-mesh-addons-ns.yaml
- gloo-mesh-ns.yaml
- gloo-mesh-relay-identity-token-secret.yaml
- gloo-mesh-relay-root-ca.yaml
- httpbin-ns.yaml
- istio-gateways-ns.yaml
- istio-system-ns.yaml
- ops-team-config-ns.yaml

commonLabels:
  istio.io/rev: 1-13

